### ISSUE TITLE
Notes can't be opened after closing and opening the app again

### ISSUE THREAD

**Issue by Dutchpainter** [0si43/PiecesOfPaper#108]
user control doesn't show up after opening app
note is archived by app 
contents of existing nots not visible after opening app

**Comment by 0si43** [comment]
@Dutchpainter 
Thanks for your feedback!

I guess, did you tap here?

![IMG_63B649D1DDB7-1](https://user-images.githubusercontent.com/45909001/148472554-8a98e3ae-e64f-494b-81aa-2c686f84f400.jpeg)

This button is an archived button.
Tap a top-right button, then your note would save in Inbox folder.

I felt some lack of explanation...
I will update the app with any navigation
