### ISSUE TITLE
Lost pages

### ISSUE THREAD

**Issue by Oshimo11** [0si43/PiecesOfPaper#110]
I had about 10 separate pages which I saved each time I used them it looks like there was an update and now my pages are gone. How do I retrieve them/find them/restore them. Thank you !

**Comment by 0si43** [comment]
Please confirm your Files app 🙏 

![IMG_1030](https://user-images.githubusercontent.com/45909001/148628668-5002f298-2c5e-40fc-a188-868bb7b4b39f.jpg)

If data transfer succeeded, your notes data would store in InboxFolder like this

![IMG_6EB97D921E6B-1](https://user-images.githubusercontent.com/45909001/148628696-7165bc55-dd69-423d-bc88-4576314dad26.jpeg)

**Comment by Oshimo11** [comment]
Whats stange is, when I first started using this App, it did not have the right side choices. It merely opened to a blank page and I canceled out and went to a page with all my pages that I had saved. Then there was an update and now my pages are gone. Anytime I opened a page, I was asked, do you want to save changes. If I made any changes then I would save again. If I was only reading, I did not.
So, as to you question, I am not certain what Files....
    On Friday, January 7, 2022, 06:44:52 PM PST, Nakajima Tsuyoshi ***@***.***> wrote:  
 
 


Please confirm your Files app 🙏
 


If data transfer succeeded, your notes data would store in InboxFolder like this



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0si43** [comment]
"Files app" is the Apple's pre-installed app, for exploring to iCloud Drive.
Note file save on iCloud Drive by default.
↓This icon

![image](https://user-images.githubusercontent.com/45909001/148670313-b3a95cc5-0de3-4afe-bd86-9daf6bd7b0b6.png)

I had attached some screenshots, maybe e-mail cannot display it...
If you have missed these picture, please access Github page↓

https://github.com/0si43/PiecesOfPaper/issues/110

**Comment by Oshimo11** [comment]
My earlier pages are not in File App…..where are the early pages

**Comment by 0si43** [comment]
Could you find the file named "converted_drawings.plist"?
It's a back-up.

If file format transfer failed, please rename "converted_drawings.plist" to "drawings.plist".
Then, open Pieces of Paper > Setting > Convert drawings.plist
You can retry the transfer action
