### ISSUE TITLE
Bug issues with App

### ISSUE THREAD

**Issue by jadamson15** [0si43/PiecesOfPaper#111]
Hi, I love this App and use it for work. However, since the update I am experiencing multiple issues. Mainly screen freeze and notes going into Archive or All folders. I can’t seem to add any additional notes to previous saved files too. I use an IPad Pro and wondered if you’ve had similar complaints and are aware of the bugs? Many thanks James

**Comment by 0si43** [comment]
Thanks James 🙏 

>  if you’ve had similar complaints and are aware of the bugs?

Maybe this issue was related……

https://github.com/0si43/PiecesOfPaper/issues/108

I will research as soon as possible!
