### ISSUE TITLE
Deleting saved apps

### ISSUE THREAD

**Issue by valesparza** [0si43/PiecesOfPaper#45]
My notes keep getting deleted even with auto saved on. Is this common?

**Comment by 0si43** [comment]
Sorry for your convenient.

Firstly, do you use iCloud?
PiecesOfPaper save your notes on iCloud by default, but if you turn off iCloud, save on your device.

![IMG_0701](https://user-images.githubusercontent.com/45909001/110570875-fb3d2580-8199-11eb-8451-416c8cca5312.jpg)
↑Please Check here!
Most Apple user use iCloud, so probably you have enabled it.

Then, please check your Files app.

![IMG_0699](https://user-images.githubusercontent.com/45909001/110571166-828a9900-819a-11eb-8ae0-673b237e154d.jpg)
![IMG_0700](https://user-images.githubusercontent.com/45909001/110571177-84ecf300-819a-11eb-8181-75d0e7cff983.jpg)
"drawings.plist" is raw data file saved your notes.
Could you check its states and attach the screenshot?

**Comment by 0si43** [comment]
This issue is not solved yet, but has left too long.
I closed this issue.

If there is any progress, re-open this issue or make another issue.
